<?php
/**
 * ABOUT VUNOTHO (Server-Rendered PHP & Tailwind CSS)
 */
require_once __DIR__ . '/api/session.php';

$pageTitle = 'About Vunotho — Zimbabwe Agricultural Operating System';
require_once __DIR__ . '/includes/header.php';
?>

<div class="max-w-4xl mx-auto space-y-12">
  
  <!-- Hero Section -->
  <div class="bg-gradient-to-br from-white via-[#FAF8F5] to-[#F1F5F9] p-8 md:p-12 rounded-3xl border border-slate-200 shadow-warm-lg">
    <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold font-mono mb-4">
      🌱 Origin & Mission • Enactus Zimbabwe
    </div>
    <h1 class="text-3xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight mb-4">
      Transforming Agriculture for <span class="text-emerald-600">Zimbabwe's Smallholders</span>
    </h1>
    <p class="text-sm md:text-base text-slate-600 leading-relaxed max-w-2xl">
      Vunotho is a specialized, decentralized agricultural operating system engineered to bridge the severe market asymmetries that plague rural smallholder farming communities across Zimbabwe.
    </p>
  </div>

  <!-- The Challenge We Address -->
  <div class="bg-white/90 backdrop-blur-md p-8 md:p-10 rounded-3xl border border-slate-200 shadow-warm-md space-y-6">
    <h2 class="text-2xl font-black text-slate-900 tracking-tight">The Core Agricultural Inefficiency in Zimbabwe</h2>
    <p class="text-xs md:text-sm text-slate-600 leading-relaxed">
      In Zimbabwe, over 70% of horticultural food production is generated by smallholder farmers operating plots of 0.5 to 5 hectares. However, due to severe geographic isolation, lack of direct freight access, and lack of real-time wholesale price transparency, smallholder farmers lose between <strong>35% and 55% of their potential income</strong> to opportunistic roadside brokers (*makoronyera*).
    </p>
    <p class="text-xs md:text-sm text-slate-600 leading-relaxed">
      Furthermore, between <strong>25% and 40% of harvested produce rots post-harvest</strong> due to strict cosmetic rejection by high-end supermarkets, leading to massive financial loss and greenhouse gas emissions in rural landfills.
    </p>
  </div>

  <!-- The Three Core Pillars of Vunotho -->
  <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
    <div class="bg-white/90 p-6 rounded-3xl border border-slate-200 shadow-warm-sm space-y-3 border-t-4 border-t-emerald-500">
      <div class="w-12 h-12 rounded-2xl bg-emerald-100 text-emerald-700 flex items-center justify-center text-2xl font-black">
        🧮
      </div>
      <h3 class="font-black text-slate-900 text-lg">1. Net-Return Price Intelligence</h3>
      <p class="text-xs text-slate-600 leading-relaxed">
        Guarantees that smallholder farmers know their exact net profit after pooled freight and coordination fees before cutting a single crop.
      </p>
    </div>

    <div class="bg-white/90 p-6 rounded-3xl border border-slate-200 shadow-warm-sm space-y-3 border-t-4 border-t-amber-500">
      <div class="w-12 h-12 rounded-2xl bg-amber-100 text-amber-700 flex items-center justify-center text-2xl font-black">
        🚚
      </div>
      <h3 class="font-black text-slate-900 text-lg">2. 2.5T Load Pooling</h3>
      <p class="text-xs text-slate-600 leading-relaxed">
        Aggregates fragmented harvests into full 2.5-tonne rural light truck manifests with sequenced waypoint collections, reducing logistics fees by 35%.
      </p>
    </div>

    <div class="bg-white/90 p-6 rounded-3xl border border-slate-200 shadow-warm-sm space-y-3 border-t-4 border-t-teal-500">
      <div class="w-12 h-12 rounded-2xl bg-teal-100 text-teal-700 flex items-center justify-center text-2xl font-black">
        ♻️
      </div>
      <h3 class="font-black text-slate-900 text-lg">3. 4-Tier Circular Bioeconomy</h3>
      <p class="text-xs text-slate-600 leading-relaxed">
        Diverts 100% of rejected produce across agro-processing, livestock feed rations, and enriched bio-compost (SDG 12.3).
      </p>
    </div>
  </div>

  <!-- Enactus Partnership Callout -->
  <div class="bg-gradient-to-r from-emerald-900 to-[#0F2942] text-white p-8 rounded-3xl shadow-warm-lg flex flex-col md:flex-row items-center justify-between gap-6">
    <div class="space-y-2">
      <span class="px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold font-mono">Academic Innovation</span>
      <h3 class="text-xl font-black">Developed with Enactus Zimbabwe</h3>
      <p class="text-xs text-slate-300 max-w-lg">
        Designed by collegiate social innovators and validated directly across active smallholder farming cooperatives in Nyanga, Gwanda, Mutasa, and Goromonzi.
      </p>
    </div>
    <a href="/why-vunotho.php" class="px-6 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black text-xs transition-all whitespace-nowrap shadow-glow-emerald">
      Explore Why Vunotho Works →
    </a>
  </div>

</div>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
