<?php
/**
 * ABOUT VUNOTHO (Server-Rendered PHP & Tailwind CSS)
 */
require_once __DIR__ . '/api/session.php';

$pageTitle = 'About Vunotho — Zimbabwe Agricultural Operating System';
require_once __DIR__ . '/includes/header.php';
?>

<div class="vn-container py-10">
  <div class="max-w-4xl mx-auto space-y-10">
    
    <!-- Hero Section -->
    <div class="bg-white/95 backdrop-blur-md p-8 md:p-12 rounded-3xl border border-emerald-100/80 shadow-sm">
      <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold font-mono mb-4">
        🌱 Origin & Mission • Enactus Zimbabwe
      </div>
      <h1 class="text-3xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight mb-4">
        Transforming Agriculture for <span class="text-emerald-700">Zimbabwe's Smallholders</span>
      </h1>
      <p class="text-sm md:text-base text-slate-600 leading-relaxed max-w-2xl">
        Vunotho is a specialized, decentralized agricultural operating system engineered to bridge the severe market asymmetries that plague rural smallholder farming communities across Zimbabwe.
      </p>
    </div>

    <!-- The Challenge We Address -->
    <div class="bg-white/95 backdrop-blur-md p-8 md:p-10 rounded-3xl border border-emerald-100/80 shadow-sm space-y-6">
      <h2 class="text-2xl font-black text-slate-900 tracking-tight">The Core Agricultural Inefficiency in Zimbabwe</h2>
      <p class="text-xs md:text-sm text-slate-600 leading-relaxed">
        In Zimbabwe, over 70% of horticultural food production is generated by smallholder farmers operating plots of 0.5 to 5 hectares. However, due to severe geographic isolation, lack of direct freight access, and lack of real-time wholesale price transparency, smallholder farmers lose between <strong>35% and 55% of their potential income</strong> to opportunistic roadside brokers.
      </p>
      <p class="text-xs md:text-sm text-slate-600 leading-relaxed">
        Furthermore, between <strong>25% and 40% of harvested produce rots post-harvest</strong> due to cosmetic rejection by supermarkets, leading to financial loss in rural landfills.
      </p>
    </div>

    <!-- The Three Core Pillars of Vunotho -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <div class="bg-white/95 p-6 rounded-3xl border border-emerald-100/80 shadow-sm space-y-3">
        <div class="w-12 h-12 rounded-2xl bg-emerald-50 text-emerald-700 flex items-center justify-center border border-emerald-100">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v12M15 9.5a2.5 2.5 0 0 0-5 0c0 3 5 2 5 5a2.5 2.5 0 0 1-5 0"/></svg>
        </div>
        <h3 class="font-black text-slate-900 text-lg">1. Net-Return Price Intelligence</h3>
        <p class="text-xs text-slate-600 leading-relaxed">
          Guarantees that smallholder farmers know their exact net profit after pooled freight and coordination fees before cutting a single crop.
        </p>
      </div>

      <div class="bg-white/95 p-6 rounded-3xl border border-emerald-100/80 shadow-sm space-y-3">
        <div class="w-12 h-12 rounded-2xl bg-orange-50 text-orange-700 flex items-center justify-center border border-orange-100">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>
        </div>
        <h3 class="font-black text-slate-900 text-lg">2. 2.5T Load Pooling</h3>
        <p class="text-xs text-slate-600 leading-relaxed">
          Aggregates fragmented harvests into full 2.5-tonne rural light truck manifests with sequenced waypoint collections, reducing logistics fees by 35%.
        </p>
      </div>

      <div class="bg-white/95 p-6 rounded-3xl border border-emerald-100/80 shadow-sm space-y-3">
        <div class="w-12 h-12 rounded-2xl bg-teal-50 text-teal-700 flex items-center justify-center border border-teal-100">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8z"/></svg>
        </div>
        <h3 class="font-black text-slate-900 text-lg">3. Circular Food Waste Diversion</h3>
        <p class="text-xs text-slate-600 leading-relaxed">
          Grades second-tier produce into verified agro-processing, canneries, and solar dehydration channels, eliminating 100% of post-harvest food waste.
        </p>
      </div>
    </div>

  </div>
</div>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
